### ISSUE TITLE
can't install (Failed to install  Homebrew)

### ISSUE THREAD

**Issue by mancin87** [rugovit/ComfyUI-Mac-Installer#1]
<img width="498" alt="image" src="https://github.com/rugovit/ComfyUI-Mac-Installer/assets/164949160/712fe319-fddc-49c9-a7e1-b5dfc2bcd584">
Hey, could you please guide a bit... i failed on first step. Homebrew cannot be installed for after i try to open startcomfyui it just gives me a blank page. Thank you. Sonoma 14.1 M1pro
<img width="413" alt="image" src="https://github.com/rugovit/ComfyUI-Mac-Installer/assets/164949160/14926bfb-77f3-4b29-a647-d78101504e6e">
 - fixed :)

**Comment by rugovit** [comment]
Yes  there is a issue with the part of the script  that  check if Brew is installed correctly,  working on it. 
In meantime  try re-running the InstallComfyUi script,  on the 2th run it will work. 
I am no able to see second screenshot "This site cannot be reached".

**Comment by rugovit** [comment]
This issue is fixed  Release  0.9.0 @mancin87
